### ISSUE TITLE
Raspberry Pi Zero PCB part completely wrong

### ISSUE THREAD

**Issue by gbaman** [fritzing/fritzing-parts#107]
I have discovered the hard way this evening after getting a set of boards sent off and manufactured, that the Raspberry Pi Zero PCB part in Fritzing is completely wrong. The headers are completely the wrong size... Rendering the boards completely useless. It seems like 2mm spacing instead of normal 2.54mm spacing between the pins.
Note the the normal Raspberry Pi model has the correct spacing, just not the Pi Zero part.

Although I hand checked a number of the parts on the board before sending it off, checking a core Fritzing part was not something I expected to have to do?

![img_1137](https://user-images.githubusercontent.com/833193/30982165-810728ac-a47e-11e7-9334-c4c58cd240a6.JPG)

**Comment by linuxlurak** [comment]
I switched to diptrace. It's the way to go... No offense!

**Comment by paulhayes** [comment]
This almost caught me out. Luckily I spotted it. Replaced my part with the beautiful one posted here. I hope this user contributed replacement gets incorporated, it's got a better schematic layout too.

**Comment by aknoerig** [comment]
Fixed via pull request 114
