### ISSUE TITLE
The new raspberry PI part doesn't load after the parts update

### ISSUE THREAD

**Issue by vanepp** [fritzing/fritzing-parts#115]
The part update for the Raspberry PI zero doesn't load after the parts update. I get Unable to find the following part "raspberry_pi_zero_rev-1.1' at 'raspberry_pi_zero-1.1.fzp' and indeed that part doesn't appear in C:\fritzing\fritzing.0.9.3b.64.pc\fritzing-parts\core (there is no zero any more). May I also suggest that we change to my radically changed version (with the GPIO pins numbered as the PI site does rather than the current numbering and has a new (and I think better) schematic. It is posted in the forums at

http://forum.fritzing.org/t/raspberry-pi-zero-fritzing-part/850/37

and I can create a pull request if that would be easier. 

Peter

**Comment by el-j** [comment]
pi zero seems ok now, any other opinions? 
closed as fixed
