### ISSUE TITLE
[fzpzclean.py] `invalid syntax` in line 21

### ISSUE THREAD

**Issue by CWempe** [fritzing/fritzing-parts#121]
I try to extract a `.fzpz` like explained in [this tutorial](https://github.com/fritzing/fritzing-parts/blob/master/CONTRIBUTING.md#how-to-export-your-part-from-within-fritzing-fzpz), but I get the following error:

```
$ python fzpzclean.py -f c:\Users\cwempe\Documents\temp\Goldcap -d c:\Users\cwempe\Documents\fritzing-parts  -o core -r
  File "fzpzclean.py", line 21
    """
      ^
SyntaxError: invalid syntax
```

It may be a local problem, but I have no experiance with python.

```
$ python -c 'import sys; print(sys.version)'
3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:54:40) [MSC v.1900 64 bit (AMD64)]
```

Any idea where the root of my problem is?
Is there another way to extract the file?

**Comment by KingDarBoja** [comment]
You have to specify the path to the .py file in order to make it work. Also, every path like _c:\Users\cwempe\Documents\temp\Goldcap_ must be enclosed by double quotes, for example: 

`python "path\to\fzpzclean.py" -f "path\to\stored_part.fzpz" -d "path\to\Fritzing-parts" -o core -r`
