### ISSUE TITLE
DB25M part missing pin 14 in schematic

### ISSUE THREAD

**Issue by noisymime** [fritzing/fritzing-parts#13]
Connector DB25M (D-SUB) from the Core library is missing pin 14 in the schematic view. The female version of this part (DB25F) includes this, but it appears to be missing from the male version.

Pin 14 of this part appears fine in the PCB and Breadboard views, it's only the schematic view that is affected. 
Looking closely, it appears than pins 14 and 15 might be placed on top of one another, but this is hard to confirm. 

Fritzing Version: 0.9.1

**Comment by el-j** [comment]
thank you
fixed
