### ISSUE TITLE
HLK-PM01 module's pcb hole sizes are too small

### ISSUE THREAD

**Issue by ashokgowtham** [fritzing/fritzing-parts#132]
I used the HLK-PM01 power supply module in a pcb design and after making the board, the holes ended up being small for the module to be placed on the board.

Then I noticed the same problem is reported on the thread where this Fritzing part originally came from (http://forum.fritzing.org/t/looking-for-a-part-hoping-someone-could-help-hlk-pm01/72/4)

I've added a pull request #133 to update the part's svg files. Please review.

**Comment by KjellMorgenstern** [comment]
PR was merged long ago
