### ISSUE TITLE
Travis-CI testing

### ISSUE THREAD

**Issue by paulvollmer** [fritzing/fritzing-parts#135]
### Context:
Use scripts from the `scripts` directory to check the parts (fzp's, svg's)

### Problem or Idea:
At the moment we have no testing/analysis of the parts. adding CI to test the quality of the parts can help the core contributors to review and check the PR.

### Solution or Next step: 

- create a list of scripts we can use for testing (we have a lot of python scripts at the `scripts` drectory)
- create a Makefile to trigger the tests (let's start at first with scripts that pass. scripts that fail can be added by separate PRs)
- create a travis config to run the tests

_/cc @el-j_

**Comment by KjellMorgenstern** [comment]
This is done in  pull request #187
