### ISSUE TITLE
Is there a way to update the parts in Linux Fritzing 0.9.1b

### ISSUE THREAD

**Issue by KeithSloan** [fritzing/fritzing-parts#14]
Is there a way to update the parts in Linux Fritzing 0.9.1b, or is the only way to build from source.
The reason I ask is that I cannot open fzp file extensions in Linux Fritzing 0.9.1b it seems to want them as fzpz. I tried ziping the fzp and renaming to fzpz but that did not work,

**Comment by el-j** [comment]
the easiest way could be to clone the parts-branch and overwrite:

	./Fritzing/parts/

solved? ;)

**Comment by el-j** [comment]
git clone https://github.com/fritzing/fritzing-parts.git

**Comment by el-j** [comment]
and delete the fzp sitting in


	./fritzing/pdb/core
	./fritzing/pdb/obsolete

otherwise there is a problem of doubled module Ids.

**Comment by KeithSloan** [comment]
Well I think I followed the steps and I now have various Raspberry Pi's in my parts/core directory, but when I run the Gui I just see Raspberry Pi B+ under Core as was the case before.

**Comment by el-j** [comment]
you have to copy the RPi B+ into the sketch,
than use the "variant"-switcher to access  the other versions. 

![image](https://cloud.githubusercontent.com/assets/2795534/6656932/7bf2e77c-cb3a-11e4-88b4-f10262279d6d.png)
