### ISSUE TITLE
Minor Issue in Schematic View for "SparkFun - storage microSD" part

### ISSUE THREAD

**Issue by bboyho** [fritzing/fritzing-parts#161]
Hi,

There was an issue filed in the SparkFun Fritzing Parts repo for a part that was created in the official Fritzing core library => [ [https://github.com/sparkfun/Fritzing_Parts/issues/15](https://github.com/sparkfun/Fritzing_Parts/issues/15) ]. Overall, the part is good except for the part's  "Schematic" view: the connectors for GND and VCC are not associated correctly with the .svg graphic.

<p align="middle"><a href="https://cloud.githubusercontent.com/assets/1015439/25646059/5b1e27a6-2f82-11e7-9033-d234d42feebe.png"><img src="https://cloud.githubusercontent.com/assets/1015439/25646059/5b1e27a6-2f82-11e7-9033-d234d42feebe.png" alt="error in Fritzing Schematic View, screenshot taken from user jmwright" title="error in Fritzing Schematic View, screenshot taken from user jmwright"></a></p>

I tried to find where it was "linked" in Fritzing's core library but I am not sure which file to correct in order to link the pins for the fritzing-parts repo. I exported the part as a new .fzpz here in case anyone needs => [ [https://github.com/sparkfun/Fritzing_Parts/blob/master/products/00544_SparkFun_storage_microsd_v1b.fzpz](https://github.com/sparkfun/Fritzing_Parts/blob/master/products/00544_SparkFun_storage_microsd_v1b.fzpz) ].

**Comment by KjellMorgenstern** [comment]
c54d1bff
