### ISSUE TITLE
Regular releases

### ISSUE THREAD

**Issue by mrueg** [fritzing/fritzing-parts#17]
Hi,
can you add a versioned release (maybe) to the corresponding fritzing-app release? That would ease packaging, right now we'd have to create snapshots every now and then.

Thanks!

**Comment by el-j** [comment]
Hej mrueg, good idea. i will have a look how this can be done. greetings

**Comment by gheja** [comment]
I believe this would be the best way to do it:
https://github.com/fritzing/fritzing-parts/releases

**Comment by el-j** [comment]
thank you very much. it's done:
https://github.com/fritzing/fritzing-parts/releases/tag/0.9.2b
