### ISSUE TITLE
ATMega 328p TQFP package has wrong pin name

### ISSUE THREAD

**Issue by Elijahg** [fritzing/fritzing-parts#18]
Pin 14 on the TQFP ATMega328 package has the wrong pin name, it's PB2 (SS/OC1B/PCINT3), but should be PB2 (SS/OC1B/PCINT2).

**Comment by el-j** [comment]
it would be nice if you can point to the exact file. i cannot confirm this bug. the tqfp atmega i see hasn't any of the "pcint" descriptions.

thanks

**Comment by Elijahg** [comment]
I'm not sure what the filename is, but I've attached screenshots of the exact part. Mousing over the pins shows the incorrect tooltip.
<img width="1332" alt="screen shot 2015-08-08 at 18 53 47" src="https://cloud.githubusercontent.com/assets/1248059/9151598/1fdc67f0-3dff-11e5-9173-062c46834406.png">
<img width="272" alt="screen shot 2015-08-08 at 18 55 02" src="https://cloud.githubusercontent.com/assets/1248059/9151600/25ab2d92-3dff-11e5-9b0a-59b7e577ffb4.png">
