### ISSUE TITLE
Unique ID for 16 Segment Display

### ISSUE THREAD

**Issue by wraybowling** [fritzing/fritzing-parts#181]
> The part '16-segment display' at '/home/pi/Documents/Fritzing/parts/core/16-segment_display.fzp' does not have a unique module id 'c8994c24e2a6d9182a55c653b6bbefed'.

**Comment by KjellMorgenstern** [comment]
I did a `git grep c8994c24e` on master and nightlyParts branches, but the only file that has this string is core/16-segment_display.fzp .

If you still see this error, please add information on how to reproduce. Most important, add the name of the other part that re-uses the same ID.
