### ISSUE TITLE
Errors in svggen.py

### ISSUE THREAD

**Issue by glixx** [fritzing/fritzing-parts#19]
```diff
File "part-gen-scripts/obsolete/fp2fzfp/svggen.py", line 24
    elif tag == "pad:
                    ^
SyntaxError: EOL while scanning string literal
Sorry: IndentationError: expected an indented block (svggen.py, line 64)
```

**Comment by aknoerig** [comment]
This script is no longer in use, hence in the "obsolete" folder. The files it generates are not compatible with current versions of Fritzing, the code only serves as a reference.

**Comment by glixx** [comment]
It should be fixed or deleted: package cannot be build.

**Comment by aknoerig** [comment]
How are you building the app? Maybe it's even better to fix the build script to exclude the obsolete folder.

**Comment by glixx** [comment]
If to build RPM package and include fritzing-parts in parts, then error will be.
Will you move all obsoletes soft into separate directory and don't include in release archive for download?
