### ISSUE TITLE
Part: Edison Breakout Board expansion header

### ISSUE THREAD

**Issue by waju0001** [fritzing/fritzing-parts#208]
J19 pin 3 is GND

in Fritzing J20 - pin 3 ist GND -  THATS WRONG 

Intel Document Number: 331190-06

**Comment by KjellMorgenstern** [comment]
It is not clear which version of the part or Fritzing this referes to, and not clear if this is Breadboard, Schematic or PCB view.

However, the only Edison related file with J20 and J19 is svg/core/pcb/intel_edison-minibreakout_bottom_pcb.svg , which is not used by any part.

The intel_edison-minibreakout_bottom uses the same PCB as the top counterpart, which makes sense (if you want to turn around the part, you do this in the PCB view)
