### ISSUE TITLE
IR receiver IR2 TSOP312 from THT paket wrong pin assignment?

### ISSUE THREAD

**Issue by MHz000** [fritzing/fritzing-parts#209]
can someone check the pin assignmet of the device pls. Vcc and GND swapt? 

I'm looking part definition of VS1838 IR receiver.

Thanks

**Comment by vanepp** [comment]
While I'm more than a bit late on this reply, a look at the tsop312 part in core indicates it is correct. The tsop312 data sheet indicates the pins are correct. To get a VS1838 (if you are still looking for one) someone (I can do it if you like) would need to modify the tsop312 part. A google search for "fritzing part VS1838" doesn't turn one up, so no one appears to have made one yet.
