### ISSUE TITLE
a problem pcb lm2596

### ISSUE THREAD

**Issue by atrinsoft** [fritzing/fritzing-parts#210]
hello
there is a problem in lm2596 module design.
in pcb part the legs are very near to each other that is encounter a problem and not correct.
the distance between legs should be standard. sincerely yours
![icon](https://cloud.githubusercontent.com/assets/22928589/19507029/13110ca6-95dd-11e6-956f-5c719f4c96b8.JPG)
![problem](https://cloud.githubusercontent.com/assets/22928589/19507037/1859bc80-95dd-11e6-94b3-6f1ee332ad9d.JPG)

**Comment by KjellMorgenstern** [comment]
The real world part does also not align with breadboard spacings. And usually, this part is also not soldered directly onto a PCB.

A fix from @vanepp was already included with 4ad4feb9502f7b7f91bd4fcbfe17553a909b8ab8 , and the obsoletion of the previous part was done in 31cf3ee8b6
