### ISSUE TITLE
Was ist los bei Fritzing?

### ISSUE THREAD

**Issue by coderfls** [fritzing/fritzing-parts#217]
Echt grausig: Auf der Fritzing-Webseite kann man keine User accounts erstellen (so bis vor kurzem, weil der Captcha-Mechanismus jahrelang überaltert war) bzw. erhält jetzt keinen Validierungscode und auf emails reagiert keiner. Wie sollen die Leute da fragen stellen oder neue Bauteiles einreichen? Ich habe echt keine Lust, dieses unmöglich komplizierte Github zu nutzen
Ich dachte es soll alles besser werden? keine Lust mehr, nachdem man so viel Aufmerksam bekommen hat?

**Comment by vanepp** [comment]
They are aware of the issue with the forum, and hopefully someone is working on it. The web site in general is in bad shape and I think they may be working on a rewrite (and thus are waiting for that rather than trying to fix the current code, although I'm not sure of that.)

Peter

**Comment by KjellMorgenstern** [comment]
@Peter exactly
@coderfls Tausende von Dateien einem Forum zu 'organisieren' und zu aktualisieren ist keine gute Idee, git ist eines der besten Tools dafür. Beschwerden über github bitte an Microsoft.
