### ISSUE TITLE
Arduino Fio silkscreen is incomplete

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-parts#281]
_From [andre.knoerig@gmail.com](https://code.google.com/u/andre.knoerig@gmail.com/) on November 14, 2012 06:20:12_

It's just showing the outline around the pin section, not the full one.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2300_

**Comment by KjellMorgenstern** [comment]
Closing, outdated part, see also #282
