### ISSUE TITLE
Arduino Fio is missing pins

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-parts#282]
_From [jim.bollansee](https://code.google.com/u/jim.bollansee/) on January 06, 2013 12:45:12_

There are some pins missing on the Arduino Fio parts definition.
The positive and negative "BAT" and "CHG" terminals on the board, to be exact.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2359_

**Comment by KjellMorgenstern** [comment]
I think the board is not used enough to justify efforts
