### ISSUE TITLE
9mm Rotary Potentiometer Wrong PCB Image

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-parts#323]
_From [bitsybof...@gmail.com](https://code.google.com/u/112850805511005419452/) on August 17, 2013 23:23:41_

Seems like the 9mm Rotary Potentiometer has an incorrect PCB image...

sqlite> select \* from parts where id = 554;
554|e55c4e524988a0331c383c6d9b004770_8|potentiometer|4||0.3.15b.02.03.3943|Lionel Michel|Rotary Potentiometer (Small)|R||A rotary adjustable resistor (potentiometer).||||0|core/starter-poti-small.fzp

sqlite> select \* from viewimages where part_id = 554;
2213|0|icon/starter-poti-small_icon.svg|1|0|0|0|554
2214|1|breadboard/starter-poti-small_breadboard.svg|4|0|0|0|554
2215|2|schematic/basic_poti.svg|1536|0|1|1|554
2216|3|pcb/starter-poti-small_pcb.svg|42991616|0|0|0|554

parts/svg/core/pcb/starter-poti-small_pcb.svg (in current git) doesn't look like a 9mm potentiometer footprint to me.

Also it seems not possible to type in a resistance for this part (and indeed other rotary pots), you only get to select from a couple of options (10k, 100k)

**Attachment:** [pot.png](http://code.google.com/p/fritzing/issues/detail?id=2718)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2718_

**Comment by failiz** [comment]
This has been fixed with the new pots. Probably still happens with the old ones, but I do no think it is worth to fix them as they can be replaced with the new ones which have a better pot symbol in the SCH view.
