### ISSUE TITLE
Arduino Pro Mini pins misplaced

### ISSUE THREAD

**Issue by niclashoyer** [fritzing/fritzing-parts#33]
The Arduino Pro Mini can't be placed correctly on any board in the breadboard view, because the pins don't connect correctly. They seem to be misplaced:

![bildschirmfoto von 2015-12-08 16-41-43](https://cloud.githubusercontent.com/assets/175808/11659843/96cfa59a-9dca-11e5-964b-1b1d9dffecc3.png)

Also see [corresponding forum thread](http://forum.fritzing.org/t/components-not-lining-up-with-perfboard/240).

**Comment by aknoerig** [comment]
See reply in the thread. I now marked the off-grid pins as female, which is the proper way for Fritzing to deal with these cases.

Fixed in commit 9bb56f5
