### ISSUE TITLE
Incorrect pinout for NPN EBC transistor

### ISSUE THREAD

**Issue by aknoerig** [fritzing/fritzing-parts#35]
_From @chrisspen on October 15, 2015 12:49_

Selecting "NPN-Transistor" with an EBC pinout type from Core/Basic parts renders with pin 1 showing as the base. However, since it's listed as "EBC", I would expect pin 1 to be emitter. Also, in every datasheet for NPN EBC transistors I've seen (e.g. [2N4401](https://www.fairchildsemi.com/.../2N4401.pdf)), pin 1 is the emitter and pin 2 is the base.

Searching for NPN transistor shows many similar parts but they all appear to render pin 1 as the base regardless of the EBC type selection.

Have I misconfigured something or am I misunderstanding how these parts are rendered?

_Copied from original issue: fritzing/fritzing-app#3147_

**Comment by el-j** [comment]
if you place all types next to each other in same direction, the naming (CBE, EBC, ECB) refers to the pinout of the legs. the numbering is just the connector numbering. the pinout is right. from my point of view.

![image](https://cloud.githubusercontent.com/assets/2795534/11749491/5ad9a19c-a02e-11e5-9b6b-f5bb2d627934.png)
