### ISSUE TITLE
Change default resistor label

### ISSUE THREAD

**Issue by KjellMorgenstern** [fritzing/fritzing-parts#356]
The "power" property of the label did not have a unit (it should be 0.25W instead of 0.25)
Since many circuits use the default of 0.25W, it makes sense to not show this in the label by default.

**Comment by KjellMorgenstern** [comment]
Default label in schematic view:
![image](https://user-images.githubusercontent.com/6494025/214643052-87b0f807-e76f-4c59-93a3-c2282535e3c2.png)

**Comment by KjellMorgenstern** [comment]
For existing circuits, the label visibilty is not changed, but the unit is now shown:
![31790581a570c80c9e8fedc2c5516b08099c933f](https://user-images.githubusercontent.com/6494025/214644023-9f0adcf0-3de6-48cf-a2f9-db4b146b025d.gif)

**Comment by failiz** [comment]
This change was in one commit of my PR:
https://github.com/fritzing/fritzing-parts/pull/344/commits/eb8b1b1b98708d121c15f295f6bcca22a987409e
