### ISSUE TITLE
New Parts Creation Process - Video Request

### ISSUE THREAD

**Issue by ThePieMonster** [fritzing/fritzing-parts#357]
The only tutorials I have found so far are the below:
https://fritzing.org/learning/tutorials/creating-custom-parts/

These are all outdated. Can we get a updated tutorial on creating custom parts? The process is pretty complex, so a video showing someone creating a part, and even uploading it, would be very helpful to the community.

**Comment by KjellMorgenstern** [comment]
There is the original blog post, about the parts editor: 
https://blog.fritzing.org/2012/10/09/new-parts-editor-released

There is a number of tutorials from the community:
https://forum.fritzing.org/c/ttutorials/24

If you prefer videos, there is are the fantastic series from OldGrey:
https://forum.fritzing.org/t/fritzing-part-creation-video-tutorial-series/2647
or directly on youtube
"Fritzing Parts Fast 1 -6" and "Fritzing Advanced Tips & Tricks 1 -4"
 https://www.youtube.com/@blackblackfalcon/video

We are also working on improving the parts editor, to reduce the need to switch between Fritzing, Inkscape or other drawing tools. 

Regarding the tutorials on fritzing.org, I'd be happy to replace or update sections.
