### ISSUE TITLE
Hint: add components

### ISSUE THREAD

**Issue by AntonioBerna** [fritzing/fritzing-parts#375]
## Problem
I need to create updated assembly diagrams with the latest microcontroller versions and not having the new Arduino boards (Minima and Wifi) on Fritzing is a problem for my projects.

## Proposed solution.
It would be useful to add the new Arduino microcontrollers to have the ability to create up-to-date assembly diagrams with Fritzing.

**Comment by KjellMorgenstern** [comment]
Still looks like a duplicate, please check the previous issue #374

I repeat, only one part per issue.

**Comment by AntonioBerna** [comment]
Okay I got it thank you. So you are working on it?

**Comment by KjellMorgenstern** [comment]
Closing as duplicate of #374
