### ISSUE TITLE
Expecting part for **Arduino UNO R4 Wifi**

### ISSUE THREAD

**Issue by jiapei100** [fritzing/fritzing-parts#388]
[Arduino UNO R4 Wifi](https://docs.arduino.cc/hardware/uno-r4-wifi) is out for more than half a year. Looking forward to its part. Clearly, from the current [fritzing-app](https://github.com/fritzing/fritzing-app) with loaded [fritzing-parts](https://github.com/fritzing/fritzing-parts), there is **NO** Arduino Board: [Arduino UNO R4 Wifi](https://docs.arduino.cc/hardware/uno-r4-wifi) 

![Fritzing_Expecting_Arduino_UNO_R4_WiFi](https://github.com/fritzing/fritzing-parts/assets/154013/ee870c32-b2c4-43f0-b076-a2c2728e7246)

**Comment by jiapei100** [comment]
Found external support. Thank you ...

**Comment by KjellMorgenstern** [comment]
Duplicate of #374
