### ISSUE TITLE
Missing DGS N-Channel Mosfet?

### ISSUE THREAD

**Issue by chrisspen** [fritzing/fritzing-parts#42]
I'm trying to design a circuit with a [ZVN3306A](http://www.redrok.com/MOSFET_ZVN3306A_60V_270mA_5O_Vth2.4_TO-92.pdf) n-channel mosfet, which has a DGS pinout.

However, when I search Fritzing for "n-channel" or "mosfet" all the mosfets only support GSD pinout. I tried switching the "variant" and "package" options, but they're all identical. Is DGS supported?

**Comment by aknoerig** [comment]
It's definitely supported, we just didn't make one yet. You're welcome to contribute one. :)

**Comment by chrisspen** [comment]
What do you mean "it's definitely supported"? If there's no part...

**Comment by chrisspen** [comment]
How do I re-order the lead numbers in the part editor? It only appears to let me edit the lead names.

**Comment by chrisspen** [comment]
When I click a connector, the "terminal point" panel says "dragging enabled", but when I go to drag the terminal point, it immediately read "dragging disabled".
