### ISSUE TITLE
Sparkfun RJ11 Socket has incorrect pins in Schematic View

### ISSUE THREAD

**Issue by Kazade** [fritzing/fritzing-parts#44]
If you add a Sparkfun RJ11 socket and connect to the pins in schematic view, you'll find they don't match the pins in PCB view. Or rather, the pins on the SVG don't match the ones they're associated with. Here is the mapping that is used:

```
Schematic               PCB
1                              5
2                              1
3                              6
4                              2
5                              3
6                              4
```

**Comment by xabixab** [comment]
I think i've fixed it, but github doesn't support the fzpz file to be upload as attachament.
