### ISSUE TITLE
Release 0.9.3b tarball

### ISSUE THREAD

**Issue by ehbello** [fritzing/fritzing-parts#54]
Please,

release the source tarball for version 0.9.3b fritzing-parts here, in github, at the same time fritzing-app to ease Fritzing Debian packaging.

Thanks.

**Comment by aknoerig** [comment]
Thanks for the hint, just tagged the release! 
Note however that since fritzing now automatically updates the parts database from github, you can just clone the latest master of fritzing-parts.
