### ISSUE TITLE
is there any chance to put both banana pi and TIs launchpads and micros?

### ISSUE THREAD

**Issue by cjdg** [fritzing/fritzing-parts#66]
Hi i would like to ask is there any chance to include TIs MCUS, Launchpads and banana pis?
Many people use them and are in libraries but not into the main one

**Comment by KjellMorgenstern** [comment]
There is a chance,but to increase it, I suggest:
Open issues one part or library a time.
Add a link to the library
Add a link to the PDF datasheets.

Closing this issue for now, as no progress has been made on it since 2016.
