### ISSUE TITLE
core.fzb Core.png: no such file or directory

### ISSUE THREAD

**Issue by paulvollmer** [fritzing/fritzing-parts#76]
```
fzb validate 0.1.0
ERROR @ "/home/travis/gopath/src/github.com/fritzing/fritzing-parts/bins/core.fzb"
ERROR > Icon File "Core.png" - open fzb/Core.png: no such file or directory
```

https://travis-ci.org/fritzing/fritzing-parts/builds/153306563#L310

where is the file located? at the fritzing-parts and at the fritzing-app no search hit...
@el-j  is the file missing?

**Comment by el-j** [comment]
the file is located in the fritzing-app resources. 
maybe the logos should move to the fritzing-parts repository as well...

**Comment by el-j** [comment]
they can be found here:
https://github.com/fritzing/fritzing-app/tree/master/resources/bins/icons
