### ISSUE TITLE
Screw Terminals are all the same size.

### ISSUE THREAD

**Issue by DarrenTownsend** [fritzing/fritzing-parts#80]
The Screw Terminal parts have options to alter the pin spacing (0.1, 0.2, etc) but this has no effect on the size of the part or the actual pin spacing on the breadboard, which stays at 0.1in.

**Comment by el-j** [comment]
thanks for pointing that out. in fact this is not an issue. 
fritzing wants to make an easy to use straight forward workflow. so therefore we take care
that most of the parts fit to the 0.1inch grid of breadboards.

if you change the pin-spacing and look at the pcb-view you can notice that the pin-spacing of the parts-footprint changes.
