### ISSUE TITLE
"Fixing" parts and version numbers

### ISSUE THREAD

**Issue by mcauser** [fritzing/fritzing-parts#82]
I noticed commits like this:
https://github.com/fritzing/fritzing-parts/commit/bd0390915f897a0d7b3f0ba943646f0f889e392d
which add "_fixed" to the module id.

This is fine for the first "fix"...
What happens when someone comes along and wants to fix your fix?
Or someone else fix the fix that fixed your fix, but didn't actually fix it, resulting in a new fix?

Do they rename the module:
* "my_part_fixed_fixed"
* "my_part_fixed_again"
* "my_part_proper_fix"
* "my_part_final"
* "my_part_fixed2"
* "my_part_last_fix"

Why not go with something more descriptive in the module ids, such as the version number?
* "my_part_v2"
* "my_part_v3"

Additionally, the How to contribute a fix section is incomplete:
https://github.com/fritzing/fritzing-parts/blob/master/CONTRIBUTING.md

**Comment by el-j** [comment]
yeah indeed there could be a better way to do the fix-versioning. important is, that every part have a unique id. if you use something like "_v2" i could come to confusion with parts like the arduino rev3. or raspi3... thats why i used to use the "fix" or "fixed" statement. 

thanks for the hint we are at the moment building a contribution check automation, so a part will be tested automatically when it comes to a pull request. 

greetings
