### ISSUE TITLE
Chirp! Soil Moisture Sensor: VCC and MISO not connectable 

### ISSUE THREAD

**Issue by lobeck** [fritzing/fritzing-parts#84]
The pins for VCC and MISO are not connectable in the breadboad view. The other 4 ports work well.

Haven't found any issues in the parts editor, so please can someone have another look why they are unavailable?

**Comment by el-j** [comment]
fixed with new parts-update. 
see [commit](https://github.com/fritzing/fritzing-parts/commit/bd4dedcba75643f38cd832a7f19cb9138111030b) for more information
