### ISSUE TITLE
The latest parts update has broken the pcb footprint for the Camdenboss_CTB0158-2_5_08mm_pitch_90deg_terminals_pcb.svg

### ISSUE THREAD

**Issue by vanepp** [fritzing/fritzing-parts#85]
The latest parts update has broken the previously working footprint for the Camdenboss_CTB0158-2_5_08mm_pitch_90deg_terminals_pcb.svg
file. There is a topic in the forums looking for a fix, and it was working for me until I checked updates and loaded the latest updates at which time I too became broken.

**Comment by el-j** [comment]
i am really sorry, i have to fix all the pcb-svgs because of many transform/translate properties, that causes trouble if the part is rotated and getting exported.

sadly i override the  Camdenboss_CTB0158-2_5_08mm_pitch_90deg_terminals_pcb.svg with the CTB0158-6 footprint.

fixed with new update

**Comment by vanepp** [comment]
Wow, fabulous service, thank you! You have my sympathy on the translates, Inkscape loves them and I find them evil and hard to eliminate (but I'm still learning to make parts).
