### ISSUE TITLE
font-size attributes should be unitless

### ISSUE THREAD

**Issue by mMerlin** [fritzing/fritzing-parts#97]
https://github.com/fritzing/fritzing-app/wiki/2.1-Part-file-format says that svg elements should always be unitless.  I have not checked everything, but had problems specifically with text elements not showing up when using File ¦ Export ¦ as Image ¦ SVG.  That was traced to existing parts having the font-size specified in pixels (px units).  I am currently using Fritzing version 0.9.2, because that is that latest that can be installed directly from the Fedora 24 repos.  The newer version is not even in the test repos yet.  

In that environment
```
grep "font-size:[0-9]*\.[0-9]*px;" /usr/share/fritzing/parts/svg/core/*/*.svg
grep "font-size=\"[0-9]*\.[0-9]*px" /usr/share/fritzing/parts/svg/core/*/*.svg
```
Finds a lot of font sizes with px units.  Piping the output of those through wc shows 295 and 44 instances, although there are not that many unique files.  Plenty of files with multiple cases of the same problem.

The up coming validation script should handle these too.  I have also seen that there may be a cleanup script in progress that would go back and fix the existing parts.

**Comment by KjellMorgenstern** [comment]
Fritzing should support the [0-9]+px notation for font sizes instead. Newer versions of Fritzing have some improvements (0.9.5dev) already.
